### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by Emperor577** [arojohnson/yii2-webcam#2]
Problem 1
    - The requested package johnson/yii2-webcam * is satisfiable by johnson/yii2-webcam[dev-master] but these conflict with your requirements or minimum-stability.

**Comment by arojohnson** [comment]
Hi Nur Muhammad, Will resolve ASAP

**Comment by Emperor577** [comment]
![image](https://user-images.githubusercontent.com/42857664/64672529-31a2c300-d485-11e9-9182-0ce26ff85a69.png)

**Comment by Emperor577** [comment]
what can you suggest instead of?

**Comment by arojohnson** [comment]
![image](https://user-images.githubusercontent.com/6159629/64673650-4e4cf400-d4a1-11e9-8e9e-94663d1d4b9d.png)

Problem has been resolved

**Comment by Emperor577** [comment]
next problem is the main function not working not capturing

**Comment by arojohnson** [comment]
Please check for hardware camera permissions are enabled or ask your doubts in Yii Framework forums
